var namespaces_dup =
[
    [ "Archive_Zip", "de/d56/namespace_archive___zip.html", null ],
    [ "class", "d7/dd6/namespaceclass.html", null ],
    [ "database", "da/df2/namespacedatabase.html", null ],
    [ "EasyLexSQL", "d1/d7d/namespace_easy_lex_s_q_l.html", null ],
    [ "kernel", "d7/da2/namespacekernel.html", null ],
    [ "Legacy", "df/ddd/namespace_legacy.html", null ],
    [ "legacy", "df/d43/namespacelegacy.html", null ],
    [ "LegacyRender", "d8/df6/namespace_legacy_render.html", null ],
    [ "legacyRender", "db/d99/namespacelegacy_render.html", null ],
    [ "Message", "db/d1b/namespace_message.html", null ],
    [ "Preload", "d4/de2/namespace_preload.html", null ],
    [ "profile", "d8/d6b/namespaceprofile.html", null ],
    [ "ShadePlus", "d4/d94/namespace_shade_plus.html", null ],
    [ "ShadeSoap", "d1/df9/namespace_shade_soap.html", null ],
    [ "Sitemap", "d1/d27/namespace_sitemap.html", null ],
    [ "stdCache", "d3/d90/namespacestd_cache.html", null ],
    [ "User", "d1/d73/namespace_user.html", null ],
    [ "user", "dc/d44/namespaceuser.html", null ],
    [ "xcat", "d2/d43/namespacexcat.html", null ],
    [ "XCL", "d4/dc9/namespace_x_c_l.html", null ],
    [ "XCube", "db/d72/namespace_x_cube.html", null ],
    [ "XOOPS2", "dd/d36/namespace_x_o_o_p_s2.html", null ],
    [ "xoops2", "d1/d3d/namespacexoops2.html", null ]
];